//login

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

//user

export const REQ_USERS_PENDING = 'REQ_USERS_PENDING';
export const REQ_USERS_SUCCESS = 'REQ_USERS_SUCCESS';
export const REQ_USERS_ERROR = 'REQ_USERS_ERROR';

export const REQ_USER_PENDING = 'REQ_USER_PENDING';
export const REQ_USER_SUCCESS = 'REQ_USER_SUCCESS';
export const REQ_USER_ERROR = 'REQ_USER_ERROR';

export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_ITEM_ERROR';

// notification

export const REQ_NOTIFICATIONS_PENDING = 'REQ_NOTIFICATIONS_PENDING';
export const REQ_NOTIFICATIONS_SUCCESS = 'REQ_NOTIFICATIONS_SUCCESS';
export const REQ_NOTIFICATIONS_ERROR = 'REQ_NOTIFICATIONS_ERROR';

export const REQ_NOTIFICATION_PENDING = 'REQ_NOTIFICATION_PENDING';
export const REQ_NOTIFICATION_SUCCESS = 'REQ_NOTIFICATION_SUCCESS';
export const REQ_NOTIFICATION_ERROR = 'REQ_NOTIFICATION_ERROR';

export const ADD_NOTIFICATION_PENDING = 'ADD_NOTIFICATION_PENDING';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR';

export const UPDATE_NOTIFICATION_PENDING = 'UPDATE_NOTIFICATION_PENDING';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_ERROR = 'UPDATE_NOTIFICATION_ERROR';

export const DELETE_NOTIFICATION_PENDING = 'DELETE_NOTIFICATION_PENDING';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';

// direct_message

export const REQ_DIRECT_MESSAGES_PENDING = 'REQ_DIRECT_MESSAGES_PENDING';
export const REQ_DIRECT_MESSAGES_SUCCESS = 'REQ_DIRECT_MESSAGES_SUCCESS';
export const REQ_DIRECT_MESSAGES_ERROR = 'REQ_DIRECT_MESSAGES_ERROR';

export const REQ_DIRECT_MESSAGE_PENDING = 'REQ_DIRECT_MESSAGE_PENDING';
export const REQ_DIRECT_MESSAGE_SUCCESS = 'REQ_DIRECT_MESSAGE_SUCCESS';
export const REQ_DIRECT_MESSAGE_ERROR = 'REQ_DIRECT_MESSAGE_ERROR';

export const ADD_DIRECT_MESSAGE_PENDING = 'ADD_DIRECT_MESSAGE_PENDING';
export const ADD_DIRECT_MESSAGE_SUCCESS = 'ADD_DIRECT_MESSAGE_SUCCESS';
export const ADD_DIRECT_MESSAGE_ERROR = 'ADD_DIRECT_MESSAGE_ERROR';

export const UPDATE_DIRECT_MESSAGE_PENDING = 'UPDATE_DIRECT_MESSAGE_PENDING';
export const UPDATE_DIRECT_MESSAGE_SUCCESS = 'UPDATE_DIRECT_MESSAGE_SUCCESS';
export const UPDATE_DIRECT_MESSAGE_ERROR = 'UPDATE_DIRECT_MESSAGE_ERROR';

export const DELETE_DIRECT_MESSAGE_PENDING = 'DELETE_DIRECT_MESSAGE_PENDING';
export const DELETE_DIRECT_MESSAGE_SUCCESS = 'DELETE_DIRECT_MESSAGE_SUCCESS';
export const DELETE_DIRECT_MESSAGE_ERROR = 'DELETE_DIRECT_MESSAGE_ERROR';

// images

export const REQ_IMAGES_PENDING = 'REQ_IMAGES_PENDING';
export const REQ_IMAGES_SUCCESS = 'REQ_IMAGES_SUCCESS';
export const REQ_IMAGES_ERROR = 'REQ_IMAGES_ERROR';

export const REQ_IMAGE_PENDING = 'REQ_IMAGE_PENDING';
export const REQ_IMAGE_SUCCESS = 'REQ_IMAGE_SUCCESS';
export const REQ_IMAGE_ERROR = 'REQ_IMAGE_ERROR';

export const ADD_IMAGE_PENDING = 'ADD_IMAGE_PENDING';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_ERROR = 'ADD_IMAGE_ERROR';

export const UPDATE_IMAGE_PENDING = 'UPDATE_IMAGE_PENDING';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_ERROR = 'UPDATE_IMAGE_ERROR';

export const DELETE_IMAGE_PENDING = 'DELETE_IMAGE_PENDING';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';

// audio

export const REQ_AUDIOS_PENDING = 'REQ_AUDIOS_PENDING';
export const REQ_AUDIOS_SUCCESS = 'REQ_AUDIOS_SUCCESS';
export const REQ_AUDIOS_ERROR = 'REQ_AUDIOS_ERROR';

export const REQ_AUDIO_PENDING = 'REQ_AUDIO_PENDING';
export const REQ_AUDIO_SUCCESS = 'REQ_AUDIO_SUCCESS';
export const REQ_AUDIO_ERROR = 'REQ_AUDIO_ERROR';

export const ADD_AUDIO_PENDING = 'ADD_AUDIO_PENDING';
export const ADD_AUDIO_SUCCESS = 'ADD_AUDIO_SUCCESS';
export const ADD_AUDIO_ERROR = 'ADD_AUDIO_ERROR';

export const UPDATE_AUDIO_PENDING = 'UPDATE_AUDIO_PENDING';
export const UPDATE_AUDIO_SUCCESS = 'UPDATE_AUDIO_SUCCESS';
export const UPDATE_AUDIO_ERROR = 'UPDATE_AUDIO_ERROR';

export const DELETE_AUDIO_PENDING = 'DELETE_AUDIO_PENDING';
export const DELETE_AUDIO_SUCCESS = 'DELETE_AUDIO_SUCCESS';
export const DELETE_AUDIO_ERROR = 'DELETE_AUDIO_ERROR';

// video

export const REQ_VIDEOS_PENDING = 'REQ_VIDEOS_PENDING';
export const REQ_VIDEOS_SUCCESS = 'REQ_VIDEOS_SUCCESS';
export const REQ_VIDEOS_ERROR = 'REQ_VIDEOS_ERROR';

export const REQ_VIDEO_PENDING = 'REQ_VIDEO_PENDING';
export const REQ_VIDEO_SUCCESS = 'REQ_VIDEO_SUCCESS';
export const REQ_VIDEO_ERROR = 'REQ_VIDEO_ERROR';

export const ADD_VIDEO_PENDING = 'ADD_VIDEO_PENDING';
export const ADD_VIDEO_SUCCESS = 'ADD_VIDEO_SUCCESS';
export const ADD_VIDEO_ERROR = 'ADD_VIDEO_ERROR';

export const UPDATE_VIDEO_PENDING = 'UPDATE_VIDEO_PENDING';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_ERROR = 'UPDATE_VIDEO_ERROR';

export const DELETE_VIDEO_PENDING = 'DELETE_VIDEO_PENDING';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_ERROR = 'DELETE_VIDEO_ERROR';

// default

// export const REQ_ITEMS_PENDING = 'REQ_ITEMS_PENDING';
// export const REQ_ITEMS_SUCCESS = 'REQ_ITEMS_SUCCESS';
// export const REQ_ITEMS_ERROR = 'REQ_ITEMS_ERROR';

// export const REQ_ITEM_PENDING = 'REQ_ITEM_PENDING';
// export const REQ_ITEM_SUCCESS = 'REQ_ITEM_SUCCESS';
// export const REQ_ITEM_ERROR = 'REQ_ITEM_ERROR';

// export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
// export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
// export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

// export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
// export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
// export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

// export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
// export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
// export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';
